# Auto-generated by /root/Galileo-Runtime/Quark_EDKII/BaseTools/BuildEnv
if [ -z "$WORKSPACE" ]
then
  export WORKSPACE=/root/Galileo-Runtime/Quark_EDKII
fi
if [ -z "$EDK_TOOLS_PATH" ]
then
  export EDK_TOOLS_PATH=/root/Galileo-Runtime/Quark_EDKII/BaseTools
fi
if [ -e /root/Galileo-Runtime/Quark_EDKII/BaseTools/Bin/Linux-x86_64 ]
then
  if [ ${PATH//root/Galileo-Runtime/Quark_EDKII/BaseTools/Bin/Linux-x86_64/} == $PATH ]
  then
    export PATH=/root/Galileo-Runtime/Quark_EDKII/BaseTools/Bin/Linux-x86_64:$PATH
  fi
fi
